
set a = createobject("wscript.shell")

mytxt1=inputbox("Message 1 a spam !","Meris","messages...")
mytxt2=inputbox("Message 2 a spam !","Meris","messages...")
mytxt3=inputbox("Message 3 a spam !","Meris","messages...")
mytxt4=inputbox("Message 4 a spam !","Meris","messages...")
mytxt5=inputbox("Message 5 a spam !","Meris","messages...")
mytxt6=inputbox("Message 6 a spam !","Meris","messages...")
mytxt7=inputbox("Message 7 a spam !","Meris","messages...")
mytxt8=inputbox("Message 8 a spam !","Meris","messages...")
mytxt9=inputbox("Message 9 a spam !","Meris","messages...")
mytxt10=inputbox("Message 10 a spam !","Meris","messages...?")
mynum=inputbox("Combien de latence voudriez vous ?","Meris","0-50") 
myspeed=inputbox("Combien de temps voudriez vous envoyer un message (milliseconde 1000=1 secondes).","Meris","1000-infini") 
mywait=inputbox("Combien MS voudriez vous ?","Meris","1-infini")

msgbox("Tu as " & mywait & " secondes pour spam ta victime !")
wscript.sleep (mywait*1000) 
for i=1 to mynum 		
	a.sendkeys (mytxt1)       
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)
	a.sendkeys (mytxt2)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt3)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt4)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt5)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt6)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt7)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt8)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt9)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
	a.sendkeys (mytxt10)   
	a.sendkeys ("{ENTER}")
	wscript.sleep (myspeed)   
next
strlol = ("- Spam Bot by: Meris - ")
	a.sendkeys (strlol)   
	a.sendkeys ("{ENTER}")
msgbox("Finished Spamming!")
